### ISSUE TITLE
Change license to a free culture license

### ISSUE THREAD

**Issue by maehr** [digihistch24/abstract-template#5]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I'd like to relicense this repo under CC-BY-SA. There is no IP to speak of, and we are making it easier for other users to reuse the template and its derivatives in other contexts.
- [x] @mtwente needs to approve the relicensing.

### What type of pull request would this be?

Other

### Any links to similar examples or other references we should review?

- https://creativecommons.org/public-domain/freeworks/

**Comment by mtwente** [comment]
Fine by me. Do we have to provide/suggest a different license for the content everybody will be adding when using the template?

**Comment by maehr** [comment]
I'd suggest a dual license. Data https://creativecommons.org/licenses/by/4.0/ and Code https://www.gnu.org/licenses/agpl-3.0 like in https://github.com/maehr/open-research-data-template/pull/14
